# Generated by Django 3.0 on 2021-04-04 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('passward', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('isUserVerified', models.BooleanField(default=False)),
                ('authToken', models.UUIDField()),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2021, 4, 4, 23, 43, 5, 872237))),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
