# Generated by Django 3.0 on 2021-04-07 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 20, 15, 17, 651474)),
        ),
    ]
