# Generated by Django 3.0 on 2021-04-07 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210407_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='authToken',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 21, 17, 53, 494512)),
        ),
    ]
