# Generated by Django 3.0 on 2021-04-07 16:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210407_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='authToken',
            field=models.UUIDField(default=uuid.UUID('dbdf0b8d-66e5-43c8-b958-bac9f990153e')),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 21, 35, 41, 112106)),
        ),
    ]
