# Generated by Django 3.0 on 2021-04-07 16:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210407_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='authToken',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 21, 38, 33, 839823)),
        ),
    ]
