# Generated by Django 3.0 on 2021-04-10 12:01

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210407_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='authToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 17, 31, 10, 370259)),
        ),
    ]
