# Generated by Django 3.0 on 2021-04-10 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210410_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('languageId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=uuid.uuid4, serialize=False)),
                ('languageName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='regex',
            fields=[
                ('regexId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regexName', models.CharField(max_length=100)),
                ('regexPattern', models.CharField(max_length=100)),
                ('regexLanguage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.language')),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 18, 9, 24, 851807)),
        ),
        migrations.CreateModel(
            name='savedRegex',
            fields=[
                ('savedRegexId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regexId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.regex')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.userDetails')),
            ],
        ),
    ]
