# Generated by Django 3.0 on 2021-04-10 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210410_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 12, 48, 1, 277160, tzinfo=utc)),
        ),
    ]
