# Generated by Django 3.0 on 2021-04-15 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20210410_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='authToken',
            new_name='userId',
        ),
        migrations.CreateModel(
            name='authToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.userDetails')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
