# Generated by Django 3.0 on 2021-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20210415_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='key',
            field=models.CharField(default='67596b1e07a6774f36cbf48a522bdd6137e222cd', max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
